Import('env')

source = Split("""
enum.ml
bitSet.ml
dynArray.ml
extArray.ml
extHashtbl.ml
extList.ml
extString.ml
global.ml
IO.ml
option.ml
pMap.ml
std.ml
uChar.ml
uTF8.ml
base64.ml
unzip.ml
refList.ml
optParse.ml
dllist.ml
extLib.ml
""")

lib = env.OcamlLibrary('extlib', source, OCAML_PATH = ['build-lib/extlib-1.5'])

Return('lib')
