name: Build Macos M1

on: push

jobs:
  build:
    name: Build code
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Install go dependencies
        run: |
          go get ./...
          go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./game/magic
