name: Build Linux

on: push

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libasound2-dev xorg-dev
          # for running the tests
          sudo apt-get -y install xvfb

      - name: Install go dependencies
        run: |
          go get ./...
          go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Test
        run: xvfb-run go test ./lib/... ./game/...

      - name: Build
        run: go build ./game/magic

  build-arm64:
    name: Build code on arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libasound2-dev xorg-dev
          # for running the tests
          sudo apt-get -y install xvfb

      - name: Install go dependencies
        run: |
          go get ./...
          go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Test
        run: xvfb-run go test ./lib/... ./game/...

      - name: Build
        run: go build ./game/magic
